@startuml カレーライス
title カレーライス
start
    :米をとぐ;
    :野菜・肉を切る;
fork 
    :お湯を沸かす; 
    :切った具材を煮込む;
    :カレールーを入れる;
    :カレー]
fork again
    :米を炊く;
    :ライス]
end fork
    :炊けた米とカレーを盛り付ける;
    :カレーライス]
stop
@enduml
