@startuml 演習3-5
left to right direction
object "<u>ホテル</u>" as hotel {
キャンペーン価格 = 9000円
一般価格 = 11000円
}
object "<u>部屋</u>" as room301 {
部屋番号 = 301
タイプ = シングル
宿泊費 = 11000円
キャンペーン価格 = 9000円
}
object "<u>部屋</u>" as room303 {
部屋番号 = 303
タイプ = シングル
宿泊費 = 11000円
キャンペーン価格 = 9000円
}
object "<u>宿泊者</u>" as guest1 {
名前 = Aさん
チェックイン日 = 5月3日
宿泊日数 = 2泊
}
object "<u>宿泊者</u>" as guest2 {
名前 = Bさん
チェックイン日 =5 月3日
宿泊日数 = 2泊
}
hotel "1" -- "0.." room301 : 部屋
hotel "1" -- "0.." room303 : 部屋
room301 "1" -- "0.." guest1 : 宿泊者
room303 "1" -- "0.." guest2 : 宿泊者
@enduml
