@startuml 演習3-7
object "高橋洋平" as k1 {
名前 = "高橋洋平"
}
object "高橋洋平さんが注文した商品" as k1o1 {
商品1 = "テレビ(V12345)"
数量1 = 2
商品2 = "冷蔵庫(R8765)"
数量2 = 1
注文日 = "11月21日"
}
object "高田利恵" as k2 {
名前 = "高田利恵"
}
object "高田利恵さんが注文した商品" as k2o1 {
商品 = "冷蔵庫(R8765)"
数量 = 1
注文日 = "12月23日"
}
object "大坪直之" as k3 {
名前 = "大坪直之"
}
object "大坪直之さんが見た商品" as k3o1 {
商品 = "プロジェクタ(P1122)"
注文日 = "12月30日"
}
k1o1 "1" -- "1" k1
k2o1 "1" -- "1" k2
k3o1 "1" -- "1" k3
@enduml