@startuml 演習6‐5‐3
state 電源OFF {
  電源OFF --> 電源ON : 電源SWをONにする
}
state 電源ON {
  [*] --> 右旋回 : 光センサーがライン上にある
  右旋回 --> 左旋回 : 光センサーがラインを外れる
  左旋回 --> 右旋回 : 光センサーがライン上にある
  右旋回 --> [*] : 光センサーがラインを外れる
}
電源ON --> 電源OFF : 電源SWをOFFにする

@enduml
