@startuml 演習4‐5

actor ":会員" as member
participant ":商品検索画面" as ui
participant ":商品検索コントローラ" as controller
participant ":商品" as item
participant ":商品カテゴリ" as category

activate member
member -> ui: 商品検索（商品番号）
    activate ui
    ui -> controller: 商品検索（商品番号）
        activate controller
        controller --> item: <<create>>生成()
        loop 商品カテゴリ数
        controller --> category: <<create>>生成()
        controller -> item: 商品カテゴリ設定()
            activate item
            deactivate item
        end loop
        controller --> ui: 商品情報
            deactivate controller
            
ui -> ui : 商品情報表示（商品情報）
activate ui
    deactivate ui

@enduml
