@startuml 演習6‐4‐1
class 自動販売機 {
}
class ボタン {
}
class 料金装置 {
    +お金を受け取る()
}
class ベンダー装置 {
    +ドリンクを運ぶ
    +お釣りを回収する
}
class ドリンク {
}

自動販売機 "1"--"10" ボタン
自動販売機 "1"--"1" 料金装置
自動販売機 "1"--"1" ベンダー装置
ベンダー装置 "1"--"10" ドリンク
@enduml