@startuml 演習7‐4‐1

class ドリンク {
    - サイズ
}

class フード {
}

class 商品 {
    - 名称
    - 単価
}

class レシピ{
}

class 注文明細 {
    - 合計
}

class 注文 {
    - 数量
    - 小計
}

class カップ {
    - 種別
}

class 材料 {
}

class ハンバーガー {
    - 種別
}

class ポテト{
    - サイズ
}

class 割引クーポン {
    - 値引き額
    - 期限
}

注文 "1..*" o-up- 注文明細
注文 "0..*" -- "0..1" 割引クーポン
注文 "0..*" -- "1" 商品
カップ --|> 商品
ドリンク "1..3" -- "0..*" カップ
フード --|> 商品
フード "1" -- "1" レシピ
ポテト --|> フード
ハンバーガー --|> フード
商品 "1" -- "1..*" 注文明細
材料 "1..*" -down-o "1..*" ハンバーガー
パン -down-|> 材料
肉 -down-|> 材料
野菜 -down-|> 材料
チーズ -down-|> 材料

@enduml
