@startuml 演習3-6
object "高橋洋平さん" as T {
    氏名 = "高橋洋平"
    資格 = "情報処理安全確保支援士"
    合格年月日 = "2020/10/21"
}

object "樋口正之さん" as H {
    氏名 = "樋口正之"
    資格 = "情報処理安全確保支援士"
}

object "LinuC試験Level1" as linuc {
    受験者 = "高橋洋平"
    合格年月日 = "2021/3/28"
}

T -- H
T -- linuc
@enduml
